package businessServirce;
// Generated 15 Mar 2016 10:16:51 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Booking generated by hbm2java
 */
public class Booking  implements java.io.Serializable {


     private BookingId id;
     private Members members;
     private Users users;
     private String isbn;
     private String author;
     private Date publishedYear;
     private String section;
     private String description;

    public Booking() {
    }

	
    public Booking(BookingId id, Members members, Users users, String isbn, String author, Date publishedYear, String section) {
        this.id = id;
        this.members = members;
        this.users = users;
        this.isbn = isbn;
        this.author = author;
        this.publishedYear = publishedYear;
        this.section = section;
    }
    public Booking(BookingId id, Members members, Users users, String isbn, String author, Date publishedYear, String section, String description) {
       this.id = id;
       this.members = members;
       this.users = users;
       this.isbn = isbn;
       this.author = author;
       this.publishedYear = publishedYear;
       this.section = section;
       this.description = description;
    }
   
    public BookingId getId() {
        return this.id;
    }
    
    public void setId(BookingId id) {
        this.id = id;
    }
    public Members getMembers() {
        return this.members;
    }
    
    public void setMembers(Members members) {
        this.members = members;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    public Date getPublishedYear() {
        return this.publishedYear;
    }
    
    public void setPublishedYear(Date publishedYear) {
        this.publishedYear = publishedYear;
    }
    public String getSection() {
        return this.section;
    }
    
    public void setSection(String section) {
        this.section = section;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


