package businessServirce;
// Generated 15 Mar 2016 10:16:51 PM by Hibernate Tools 4.3.1



/**
 * BookingId generated by hbm2java
 */
public class BookingId  implements java.io.Serializable {


     private int bookingId;
     private int usersUserId;
     private int membersMemberId;

    public BookingId() {
    }

    public BookingId(int bookingId, int usersUserId, int membersMemberId) {
       this.bookingId = bookingId;
       this.usersUserId = usersUserId;
       this.membersMemberId = membersMemberId;
    }
   
    public int getBookingId() {
        return this.bookingId;
    }
    
    public void setBookingId(int bookingId) {
        this.bookingId = bookingId;
    }
    public int getUsersUserId() {
        return this.usersUserId;
    }
    
    public void setUsersUserId(int usersUserId) {
        this.usersUserId = usersUserId;
    }
    public int getMembersMemberId() {
        return this.membersMemberId;
    }
    
    public void setMembersMemberId(int membersMemberId) {
        this.membersMemberId = membersMemberId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BookingId) ) return false;
		 BookingId castOther = ( BookingId ) other; 
         
		 return (this.getBookingId()==castOther.getBookingId())
 && (this.getUsersUserId()==castOther.getUsersUserId())
 && (this.getMembersMemberId()==castOther.getMembersMemberId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getBookingId();
         result = 37 * result + this.getUsersUserId();
         result = 37 * result + this.getMembersMemberId();
         return result;
   }   


}


