package businessServirce;
// Generated 15 Mar 2016 10:16:51 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Lending generated by hbm2java
 */
public class Lending  implements java.io.Serializable {


     private LendingId id;
     private int userId;
     private int bookingId;
     private Date bookingDate;
     private Date returnDate;

    public Lending() {
    }

    public Lending(LendingId id, int userId, int bookingId, Date bookingDate, Date returnDate) {
       this.id = id;
       this.userId = userId;
       this.bookingId = bookingId;
       this.bookingDate = bookingDate;
       this.returnDate = returnDate;
    }
   
    public LendingId getId() {
        return this.id;
    }
    
    public void setId(LendingId id) {
        this.id = id;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public int getBookingId() {
        return this.bookingId;
    }
    
    public void setBookingId(int bookingId) {
        this.bookingId = bookingId;
    }
    public Date getBookingDate() {
        return this.bookingDate;
    }
    
    public void setBookingDate(Date bookingDate) {
        this.bookingDate = bookingDate;
    }
    public Date getReturnDate() {
        return this.returnDate;
    }
    
    public void setReturnDate(Date returnDate) {
        this.returnDate = returnDate;
    }




}


