package businessServirce;
// Generated 15 Mar 2016 10:16:51 PM by Hibernate Tools 4.3.1



/**
 * LendingId generated by hbm2java
 */
public class LendingId  implements java.io.Serializable {


     private int lendingId;
     private int membersMemberId;

    public LendingId() {
    }

    public LendingId(int lendingId, int membersMemberId) {
       this.lendingId = lendingId;
       this.membersMemberId = membersMemberId;
    }
   
    public int getLendingId() {
        return this.lendingId;
    }
    
    public void setLendingId(int lendingId) {
        this.lendingId = lendingId;
    }
    public int getMembersMemberId() {
        return this.membersMemberId;
    }
    
    public void setMembersMemberId(int membersMemberId) {
        this.membersMemberId = membersMemberId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LendingId) ) return false;
		 LendingId castOther = ( LendingId ) other; 
         
		 return (this.getLendingId()==castOther.getLendingId())
 && (this.getMembersMemberId()==castOther.getMembersMemberId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getLendingId();
         result = 37 * result + this.getMembersMemberId();
         return result;
   }   


}


