package businessServirce;
// Generated 15 Mar 2016 10:16:51 PM by Hibernate Tools 4.3.1



/**
 * Payment generated by hbm2java
 */
public class Payment  implements java.io.Serializable {


     private PaymentId id;
     private int amount;

    public Payment() {
    }

    public Payment(PaymentId id, int amount) {
       this.id = id;
       this.amount = amount;
    }
   
    public PaymentId getId() {
        return this.id;
    }
    
    public void setId(PaymentId id) {
        this.id = id;
    }
    public int getAmount() {
        return this.amount;
    }
    
    public void setAmount(int amount) {
        this.amount = amount;
    }




}


